services:
  wallet-service:
    build:
      context: ./  # Path to the wallet service
      dockerfile: Dockerfile
    ports:
      - "8083:8081"  # external HTTP
      - "8084:8082"  # internal HTTP
      - "50052:50051"  # gRPC
    environment:
      - DB_HOST=wallet-postgres
      - REDIS_HOST=wallet-redis
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - wallet-postgres
      - wallet-redis

  wallet-postgres:
    image: postgres:latest
    container_name: wallet-service-pgsql
    environment:
      POSTGRES_DB: wallet-service
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - wallet_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  wallet-redis:
    image: redis:latest
    container_name: wallet-service-cache
    ports:
      - "6380:6379"
    volumes:
      - wallet_redis_data:/data
    networks:
      - app-network

volumes:
  wallet_postgres_data:
  wallet_redis_data:


networks:
  app-network:
    external: true