// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.0
// source: proto/asset_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetTypes []string `protobuf:"bytes,1,rep,name=asset_types,json=assetTypes,proto3" json:"asset_types,omitempty"` // e.g. ["gold", "silver"]
}

func (x *AssetPriceRequest) Reset() {
	*x = AssetPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_asset_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPriceRequest) ProtoMessage() {}

func (x *AssetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPriceRequest.ProtoReflect.Descriptor instead.
func (*AssetPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{0}
}

func (x *AssetPriceRequest) GetAssetTypes() []string {
	if x != nil {
		return x.AssetTypes
	}
	return nil
}

type PriceDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buy  float64 `protobuf:"fixed64,1,opt,name=buy,proto3" json:"buy,omitempty"`
	Sell float64 `protobuf:"fixed64,2,opt,name=sell,proto3" json:"sell,omitempty"`
}

func (x *PriceDetails) Reset() {
	*x = PriceDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_asset_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceDetails) ProtoMessage() {}

func (x *PriceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceDetails.ProtoReflect.Descriptor instead.
func (*PriceDetails) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{1}
}

func (x *PriceDetails) GetBuy() float64 {
	if x != nil {
		return x.Buy
	}
	return 0
}

func (x *PriceDetails) GetSell() float64 {
	if x != nil {
		return x.Sell
	}
	return 0
}

type AssetPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prices map[string]*PriceDetails `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // e.g. {"gold": {"buy": 1000, "sell": 1100}}
}

func (x *AssetPriceResponse) Reset() {
	*x = AssetPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_asset_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPriceResponse) ProtoMessage() {}

func (x *AssetPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPriceResponse.ProtoReflect.Descriptor instead.
func (*AssetPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{2}
}

func (x *AssetPriceResponse) GetPrices() map[string]*PriceDetails {
	if x != nil {
		return x.Prices
	}
	return nil
}

var File_proto_asset_service_proto protoreflect.FileDescriptor

var file_proto_asset_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x22, 0x34, 0x0a, 0x11, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x75, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x62, 0x75, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65,
	0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x6c, 0x22, 0xa3,
	0x01, 0x0a, 0x12, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x73, 0x1a, 0x4e, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x32, 0x54, 0x0a, 0x0c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x6f,
	0x6c, 0x64, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_asset_service_proto_rawDescOnce sync.Once
	file_proto_asset_service_proto_rawDescData = file_proto_asset_service_proto_rawDesc
)

func file_proto_asset_service_proto_rawDescGZIP() []byte {
	file_proto_asset_service_proto_rawDescOnce.Do(func() {
		file_proto_asset_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_asset_service_proto_rawDescData)
	})
	return file_proto_asset_service_proto_rawDescData
}

var file_proto_asset_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_asset_service_proto_goTypes = []interface{}{
	(*AssetPriceRequest)(nil),  // 0: asset.AssetPriceRequest
	(*PriceDetails)(nil),       // 1: asset.PriceDetails
	(*AssetPriceResponse)(nil), // 2: asset.AssetPriceResponse
	nil,                        // 3: asset.AssetPriceResponse.PricesEntry
}
var file_proto_asset_service_proto_depIdxs = []int32{
	3, // 0: asset.AssetPriceResponse.prices:type_name -> asset.AssetPriceResponse.PricesEntry
	1, // 1: asset.AssetPriceResponse.PricesEntry.value:type_name -> asset.PriceDetails
	0, // 2: asset.AssetService.GetAssetPrice:input_type -> asset.AssetPriceRequest
	2, // 3: asset.AssetService.GetAssetPrice:output_type -> asset.AssetPriceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_asset_service_proto_init() }
func file_proto_asset_service_proto_init() {
	if File_proto_asset_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_asset_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_asset_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_asset_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_asset_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asset_service_proto_goTypes,
		DependencyIndexes: file_proto_asset_service_proto_depIdxs,
		MessageInfos:      file_proto_asset_service_proto_msgTypes,
	}.Build()
	File_proto_asset_service_proto = out.File
	file_proto_asset_service_proto_rawDesc = nil
	file_proto_asset_service_proto_goTypes = nil
	file_proto_asset_service_proto_depIdxs = nil
}
