services:
  user-service:
    build:
      context: ./  # Path to the user service
      dockerfile: Dockerfile
    ports:
      - "8085:8081"  # external HTTP
      - "8086:8082"  # internal HTTP
      - "50053:50051"  # gRPC
    environment:
      - DB_HOST=user-postgres
      - REDIS_HOST=user-redis
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - user-postgres
      - user-redis

  user-postgres:
    image: postgres:latest
    container_name: user-service-pgsql
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  user-redis:
    image: redis:latest
    container_name: user-service-cache
    ports:
      - "6381:6379"
    volumes:
      - user_redis_data:/data
    networks:
      - app-network

  user-minio:
    image: minio/minio:latest
    container_name: user-service-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    networks:
        - app-network
    command: server /data --console-address ":9001"

volumes:
  user_postgres_data:
  user_redis_data:

networks:
  app-network:
    external: true