services:
  postgres:
    image: postgres:latest
    container_name: trading-service-pgsql
    environment:
      POSTGRES_DB: trading-service
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: 123456
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - redis-network

  redis:
    image: redis:latest
    container_name: trading-service-cache
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-network

volumes:
  postgres_data:
  redis_data:

networks:
  redis-network:
    driver: bridge